// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ModelGenerator.Core.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\kunvu\source\repos\ModelGenerator\ModelGenerator.Core.Refined\Template\ConsumerServiceBased_CSharp.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ConsumerServiceBased_CSharp : ConsumerServiceBased_CSharpBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ");
            
            #line 20 "C:\Users\kunvu\source\repos\ModelGenerator\ModelGenerator.Core.Refined\Template\ConsumerServiceBased_CSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(".Repositories.Based\r\n{\r\n\tpublic class Response<T>\r\n\t{\r\n\t\tpublic bool Success { ge" +
                    "t; set; }\r\n\t\tpublic string Message { get; set; }\r\n\t\tpublic T Data { get; set; }\r" +
                    "\n\t}\r\n    /// <summary>\r\n    /// Consumer service designed for HTTP request servi" +
                    "ces.\r\n    /// </summary>\r\n    /// <typeparam name=\"T\"></typeparam>\r\n    /// <typ" +
                    "eparam name=\"TDatabase\"></typeparam>\r\n    /// <typeparam name=\"TParameter\"></typ" +
                    "eparam>\r\n    public abstract partial class ConsumerService<T>\r\n        where T :" +
                    " class, new()\r\n    {\r\n\t\tprivate const string URL_PATH = \"https://www.someserver." +
                    "com\";\r\n        /// <summary>\r\n        /// Constructor.\r\n        /// </summary>\r\n" +
                    "        public ConsumerService()\r\n        {\r\n\r\n        }\r\n\t\tprotected abstract s" +
                    "tring ControllerName { get; }\r\n\t\tpublic async Task<Response<T>> GetAsync()\r\n\t\t{\r" +
                    "\n\t\t\tvar url = $\"{URL_PATH}/api/{ControllerName}\";\r\n\t\t\tusing (var httpClient = ne" +
                    "w HttpClient())\r\n            {\r\n                var request = await httpClient.G" +
                    "etAsync(url);\r\n                var json = await request.Content.ReadAsStringAsyn" +
                    "c();\r\n                var response = JsonConvert.DeserializeObject<Response<T>>(" +
                    "json);\r\n                return response;\r\n            }\r\n\t\t}\r\n\t\tpublic async Tas" +
                    "k<Response<T>> GetAsync(string id)\r\n\t\t{\r\n\t\t\tvar url = $\"{URL_PATH}/api/{Controll" +
                    "erName}/{id}\";\r\n\t\t\tusing (var httpClient = new HttpClient())\r\n            {\r\n   " +
                    "             var request = await httpClient.GetAsync(url);\r\n                var " +
                    "json = await request.Content.ReadAsStringAsync();\r\n                var response " +
                    "= JsonConvert.DeserializeObject<Response<T>>(json);\r\n                return resp" +
                    "onse;\r\n            }\r\n\t\t}\r\n\t\tpublic async Task<Response<T>> PostAsync(T body)\r\n\t" +
                    "\t{\r\n\t\t\tvar url = $\"{URL_PATH}/api/{ControllerName}\";\r\n\t\t\tusing (var httpClient =" +
                    " new HttpClient())\r\n            {\r\n                var content = new StringConte" +
                    "nt(JsonConvert.SerializeObject(body), Encoding.UTF8, \"application/json\");\r\n     " +
                    "           var request = await httpClient.PostAsync(url, content);\r\n            " +
                    "    var json = await request.Content.ReadAsStringAsync();\r\n                var r" +
                    "esponse = JsonConvert.DeserializeObject<Response<T>>(json);\r\n                ret" +
                    "urn response;\r\n            }\r\n\t\t}\r\n\t\tpublic async Task<Response<T>> PatchAsync(s" +
                    "tring id,T body)\r\n\t\t{\r\n\t\t\tvar url = $\"{URL_PATH}/api/{ControllerName}/{id}\";\r\n  " +
                    "          using (var httpClient = new HttpClient())\r\n            {\r\n            " +
                    "    var content = new StringContent(JsonConvert.SerializeObject(body), Encoding." +
                    "UTF8, \"application/json\");\r\n                var request = await httpClient.Patch" +
                    "Async(url, content);\r\n                var json = await request.Content.ReadAsStr" +
                    "ingAsync();\r\n                var response = JsonConvert.DeserializeObject<Respon" +
                    "se<T>>(json);\r\n                return response;\r\n            }\r\n\t\t}\r\n\t\tpublic as" +
                    "ync Task<Response<T>> DeleteAsync(string id)\r\n\t\t{\r\n\t\t\tvar url = $\"{URL_PATH}/api" +
                    "/{ControllerName}/{id}\";\r\n            using (var httpClient = new HttpClient())\r" +
                    "\n            {\r\n                var request = await httpClient.DeleteAsync(url);" +
                    "\r\n                var json = await request.Content.ReadAsStringAsync();\r\n       " +
                    "         var response = JsonConvert.DeserializeObject<Response<T>>(json);\r\n     " +
                    "           return response;\r\n            }\r\n\t\t}\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 106 "C:\Users\kunvu\source\repos\ModelGenerator\ModelGenerator.Core.Refined\Template\ConsumerServiceBased_CSharp.tt"

	public string Namespace {get; set;} = "YourNamespace";

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ConsumerServiceBased_CSharpBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
